clean up omnibus installer error and remove chef-fips
clean up the warning in #8484

also removes the chef-fips package-scripts directory which we don't
use because the purpose-built fips build went away a long time ago
(but nobody cleaned up the cruft).

closes #8484

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

diff --git a/omnibus/package-scripts/chef/preinst b/omnibus/package-scripts/chef/preinst
--- a/omnibus/package-scripts/chef/preinst
+++ b/omnibus/package-scripts/chef/preinst
@@ -8,14 +8,16 @@
 # - if you are under 40, get peer review from your elders.
 
 INSTALLER_DIR=/opt/chef
-echo "removing $INSTALLER_DIR..."
+if [ -e $INSTALLER_DIR ]; then
+  echo "removing $INSTALLER_DIR..."
 
-# have to do this dance of moving /opt/chef to a tmp dir since files may be in use
-tmp_dir="/opt/.chef.$$"
-# if we can't create the tmp_dir then fail hard to prevent any possible security hole
-(umask 077 && mkdir $tmp_dir) || exit 1
-# now we can clean up the tmp_dir we created safely
-mv $INSTALLER_DIR $tmp_dir
-# ignore errors which must be EBUSY issues, this may crate some litter, which may
-# be unavoidable
-rm -rf $tmp_dir || true
+  # have to do this dance of moving /opt/chef to a tmp dir since files may be in use
+  tmp_dir="/opt/.chef.$$"
+  # if we can't create the tmp_dir then fail hard to prevent any possible security hole
+  (umask 077 && mkdir $tmp_dir) || exit 1
+  # now we can clean up the tmp_dir we created safely
+  mv $INSTALLER_DIR $tmp_dir
+  # ignore errors which must be EBUSY issues, this may crate some litter, which may
+  # be unavoidable
+  rm -rf $tmp_dir || true
+fi
