update test for AIX
- bourne -> /bin/sh changes
- include bff support
- can't use presence of tools to determine which package to install

diff --git a/jenkins/client-test b/jenkins/client-test
--- a/jenkins/client-test
+++ b/jenkins/client-test
@@ -12,20 +12,8 @@
 set -e
 set -x
 
-# Check whether a command exists - returns 0 if it does, 1 if it does not
-exists()
-{
-  if command -v $1 >/dev/null 2>&1
-  then
-    return 0
-  else
-    return 1
-  fi
-}
-
 # SmartOS builds in /opt/local instead
-is_smartos()
-{
+is_smartos() {
   uname -v | grep "^joyent" 2>&1 >/dev/null
 }
 
@@ -39,34 +27,46 @@ fi
 mv $BUILD_NUMBER/build_timestamp $WORKSPACE/
 cd $BUILD_NUMBER
 
-# remove the chef package / clobber the files
-if exists dpkg;
-then
-    sudo dpkg -P chef || true
-elif exists rpm;
-then
-    sudo rpm -ev chef || true
-elif exists pkgadd;
-then
-    cat <<EOF > /tmp/nocheck
-conflict=nocheck
-action=nocheck
-EOF
-    if ! sudo pkgrm -a /tmp/nocheck -n chef; then
-      echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING"
-      echo "The postrm script from the *prior* installation has broken on Solaris."
-      echo "Removing that script so that subsequent pkgadd's will succeed."
-      echo "The fact that you can run this again and it does not break does not necessarily"
-      echo "mean that you can ignore this warning.  This test will flap red and green even"
-      echo "though the postremove script is always broken.  Investigate the postremove script"
-      echo "and determine WHY it failed, and make sure you use 20th century /bin/sh to test it."
-      echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING"
-      sudo rm -f /var/sadm/pkg/chef/install/postremove || true
-      exit 1
-    fi
-else # makeself installer
-  :  # intentionally left blank
+# determine install method via the package suffix
+if test -n "`ls pkg/chef*.deb 2>/dev/null`"; then
+  package_file=`ls pkg/bar*.deb`
+  filetype="deb"
+elif test -n "`ls pkg/chef*.rpm 2>/dev/null`"; then
+  package_file=`ls pkg/bar*.rpm`
+  filetype="rpm"
+elif test -n "`ls pkg/chef*.solaris 2>/dev/null`"; then
+  package_file=`ls pkg/chef*.solaris`
+  filetype="solaris"
+elif test -n "`ls pkg/chef*.bff 2>/dev/null`"; then
+  package_file=`ls pkg/chef*.bff`
+  filetype="bff"
+elif test -n "`ls pkg/chef*.sh 2>/dev/null`"; then
+  package_file=`ls pkg/chef*.sh`
+  filetype="sh"
 fi
+
+# remove the chef package / clobber the files
+case "$filetype" in
+  "deb")
+    sudo dpkg -P chef || true
+    ;;
+  "rpm")
+    sudo rpm -ev chef || true
+    ;;
+  "solaris")
+    if ! sudo pkgrm -a /tmp/nocheck -n chef; then
+      echo "WARNING: CLEANING UP BROKEN POSTRM FROM PRIOR INSTALLATION!!!!!!!!!!!!!!!!!!!!!!"
+      sudo rm -f /var/sadm/pkg/chef/install/postremove || true
+      sudo pkgrm -a /tmp/nocheck -n chef || true
+    fi
+    ;;
+  "bff")
+    installp -u chef || true
+    ;;
+  "sh")
+    # intentionally left blank
+    ;;
+esac
 
 sudo rm -rf /opt/chef/*
 
@@ -79,37 +79,33 @@ sudo rm -f $PREFIX/bin/knife || true
 sudo rm -f $PREFIX/bin/shef || true
 sudo rm -f $PREFIX/bin/ohai || true
 
+
 # install the new package
-if exists dpkg;
-then
-    sudo dpkg -i pkg/chef*.deb
-elif exists rpm;
-then
-    sudo rpm -Uvh pkg/chef*.rpm
-elif exists pkgadd;
-then
-    sudo pkgadd -n -d pkg/chef*.solaris -a /tmp/nocheck chef
-else # makeself installer
-    sudo ./pkg/chef*.sh || true
-fi
+case "$filetype" in
+  "deb") sudo dpkg -i pkg/chef*.deb ;;
+  "rpm") sudo rpm -Uvh pkg/chef*.rpm ;;
+  "solaris") sudo pkgadd -n -d pkg/chef*.solaris -a /tmp/nocheck chef ;;
+  "bff") installp -a -d pkg/chef*.bff ;;
+  "sh") sudo ./pkg/chef*.sh ;;
+esac
 
 # sanity check that we're getting symlinks from the pre-install script
-if [ ! -e "/usr/bin/chef-client" ]; then
+if [ ! -f "/usr/bin/chef-client" ]; then
   echo "/usr/bin/chef-client symlink was not installed by pre-install script!"
   exit 1
 fi
 
-if [ ! -e "/usr/bin/knife" ]; then
+if [ ! -f "/usr/bin/knife" ]; then
   echo "/usr/bin/knife symlink was not installed by pre-install script!"
   exit 1
 fi
 
-if [ ! -e "/usr/bin/chef-solo" ]; then
+if [ ! -f "/usr/bin/chef-solo" ]; then
   echo "/usr/bin/chef-solo symlink was not installed by pre-install script!"
   exit 1
 fi
 
-if [ ! -e "/usr/bin/ohai" ]; then
+if [ ! -f "/usr/bin/ohai" ]; then
   echo "/usr/bin/ohai symlink was not installed by pre-install script!"
   exit 1
 fi
@@ -127,3 +123,23 @@ sudo env PATH=$PATH TERM=xterm rspec -r rspec_junit_formatter -f RspecJunitForma
 # clean up the workspace to save disk space
 cd $WORKSPACE
 rm -rf $BUILD_NUMBER
+
+# remove the package, break the build if the postrm fails
+case "$filetype" in
+  "deb")
+    sudo dpkg -P chef
+    ;;
+  "rpm")
+    sudo rpm -ev chef
+    ;;
+  "solaris")
+    sudo pkgrm -a /tmp/nocheck -n chef
+    ;;
+  "bff")
+    installp -u chef
+    ;;
+  "sh")
+    # intentionally left blank
+    ;;
+esac
+
