numerous fixes for install scripts
- conditionally setup symlinks for chef-10-vs-chef-11
- syntax fixes for solaris

diff --git a/package-scripts/chef/postinst b/package-scripts/chef/postinst
--- a/package-scripts/chef/postinst
+++ b/package-scripts/chef/postinst
@@ -1,4 +1,5 @@
 #!/bin/bash
+# ^^^^^^^^^ this is ignored on solaris 9 and run under /bin/sh
 #
 # Install a full Opscode Client
 #
@@ -10,13 +11,13 @@ USAGE="usage: $0 [-v validation_key] ([-o organization] || [-u url])"
 
 error_exit()
 {
-	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
-	exit 1
+  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  exit 1
 }
 
 is_smartos()
 {
-  uname -v | grep ^joyent 2>&1>/dev/null
+  uname -v | grep "^joyent" 2>&1 >/dev/null
 }
 
 if is_smartos; then
@@ -35,9 +36,9 @@ do
       v)  validation_key="${OPTARG}";;
       o)  organization="${OPTARG}"; chef_url="https://api.opscode.com/organizations/${OPTARG}";;
       u)  chef_url="${OPTARG}";;
-      \?)		# unknown flag
-      	  echo >&2 ${USAGE}
-	  exit 1;;
+      \?)    # unknown flag
+          echo >&2 ${USAGE}
+    exit 1;;
     esac
 done
 shift `expr ${OPTIND} - 1`
@@ -67,17 +68,28 @@ fi
 # rm -f before ln -sf is required for solaris 9
 rm -f $PREFIX/bin/chef-client
 rm -f $PREFIX/bin/chef-solo
+rm -f $PREFIX/bin/chef-apply
+rm -f $PREFIX/bin/chef-shell
 rm -f $PREFIX/bin/knife
 rm -f $PREFIX/bin/shef
 rm -f $PREFIX/bin/ohai
 
-ln -sf $INSTALLER_DIR/bin/chef-client $PREFIX/bin || error_exit "Cannot link chef-client to $PREFIX/bin"
 ln -sf $INSTALLER_DIR/bin/chef-solo $PREFIX/bin || error_exit "Cannot link chef-solo to $PREFIX/bin"
-ln -sf $INSTALLER_DIR/bin/chef-apply $PREFIX/bin || error_exit "Cannot link chef-apply to $PREFIX/bin"
-ln -sf $INSTALLER_DIR/bin/chef-shell $PREFIX/bin || error_exit "Cannot link chef-shell to $PREFIX/bin"
+if [ -f "$INSTALLER_DIR/bin/chef-apply" ]; then
+  ln -sf $INSTALLER_DIR/bin/chef-apply $PREFIX/bin || error_exit "Cannot link chef-apply to $PREFIX/bin"
+fi
+if [ -f "$INSTALLER_DIR/bin/chef-shell" ]; then
+  ln -sf $INSTALLER_DIR/bin/chef-shell $PREFIX/bin || error_exit "Cannot link chef-shell to $PREFIX/bin"
+fi
 ln -sf $INSTALLER_DIR/bin/knife $PREFIX/bin || error_exit "Cannot link knife to $PREFIX/bin"
-ln -sf $INSTALLER_DIR/bin/shef $PREFIX/bin || error_exit "Cannot link shef to $PREFIX/bin"
+if [ -f "$INSTALLER_DIR/bin/shef" ]; then
+  ln -sf $INSTALLER_DIR/bin/shef $PREFIX/bin || error_exit "Cannot link shef to $PREFIX/bin"
+fi
 ln -sf $INSTALLER_DIR/bin/ohai $PREFIX/bin || error_exit "Cannot link ohai to $PREFIX/bin"
+
+# We test for the presence of /usr/bin/chef-client to know if this script succeeds, so this
+# must appear as the last real action in the script
+ln -sf $INSTALLER_DIR/bin/chef-client $PREFIX/bin || error_exit "Cannot link chef-client to $PREFIX/bin"
 
 echo "Thank you for installing Chef!"
 
